baseURL = 'https://sparkfysio.com'
title = 'Spark Fysio'
theme = 'ananke'

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10
  [languages.nl]
    contentDir = 'content/nl'
    languageName = 'Nederlands'
    weight = 20
